#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: Releasing in the Plugins directory

on:
  push:
    paths:
      - 'version.php'

jobs:
  workflow_master_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/master-release.yml@main
    with:
      plugin_name: auth_enrolkey
      plugin_branch: master
      plugin_repository_url: https://github.com/catalyst/moodle-auth_enrolkey
